[colors.primary]
background = "#111418"
foreground = "#e1e2e8"
dim_foreground = "#c3c6cf"

[colors.cursor]
text = "#00325a"
cursor = "#a2c9fd"

[colors.selection]
text = "#253141"
background = "#bbc7db"

[colors.normal]
black = "#32353a"
red     = "#ffb4ab"
green   = "#d7bde4"
yellow  = "#3c4858"
blue    = "#a2c9fd"
magenta = "#533f5f"
cyan    = "#bbc7db"
white   = "#e1e2e8"

[colors.bright]
black = "#43474e"
red     = "#93000a"
green   = "#f4daff"
yellow  = "#d7e3f8"
blue    = "#d2e4ff"
magenta = "#d7bde4"
cyan    = "#bbc7db"
white   = "#c3c6cf"
