[colors.primary]
background = "{{colors.background.default.hex}}"
foreground = "{{colors.on_background.default.hex}}"
dim_foreground = "{{colors.on_surface_variant.default.hex}}"

[colors.cursor]
text = "{{colors.on_primary.default.hex}}"
cursor = "{{colors.primary.default.hex}}"

[colors.selection]
text = "{{colors.on_secondary.default.hex}}"
background = "{{colors.secondary.default.hex}}"

[colors.normal]
black = "{{colors.surface_container_highest.default.hex}}"
red     = "{{colors.error.default.hex}}"
green   = "{{colors.tertiary.default.hex}}"
yellow  = "{{colors.secondary_container.default.hex}}"
blue    = "{{colors.primary.default.hex}}"
magenta = "{{colors.tertiary_container.default.hex}}"
cyan    = "{{colors.secondary.default.hex}}"
white   = "{{colors.on_surface.default.hex}}"

[colors.bright]
black = "{{colors.outline_variant.default.hex}}"
red     = "{{colors.error_container.default.hex}}"
green   = "{{colors.tertiary_fixed.default.hex}}"
yellow  = "{{colors.secondary_fixed.default.hex}}"
blue    = "{{colors.primary_fixed.default.hex}}"
magenta = "{{colors.tertiary_fixed_dim.default.hex}}"
cyan    = "{{colors.secondary_fixed_dim.default.hex}}"
white   = "{{colors.on_surface_variant.default.hex}}"
